### ISSUE TITLE
how to install SCC package?

### ISSUE THREAD

**Issue by Yenwod** [riverbed/steelscript#2]
After following the Steelscript installation instructions multiple times, I have not been able to install the SCC package.  How would you actually go about installing it?

After installation when following the [SCC tutorial](https://support.riverbed.com/apis/steelscript/scc/tutorial.html), in Section 10.2.3 this line of code works:
```python
from steelscript.common.service import OAuth
```
while this line fails:
```python
from steelscript.scc.core import SCC
```
with the error:
```bash
ImportError: No module named scc.core
```

**Comment by mgarabed** [comment]
Seems like the base steelscript package got installed but not the steelscript.scc package.

Can you provide the output of the command `steel about`?

It should be as simple as running `pip install steelscript.scc` which should cover all of the additional dependencies.

You might also need to upgrade your pip: `pip install --upgrade pip`

**Comment by Yenwod** [comment]
@mgarabed - thanks!  Running `pip install steelscript.scc` did the trick!
